### ISSUE TITLE
Suggestion: Move to Python 3 for Ubuntu hosts

### ISSUE THREAD

**Issue by ghost** [robertdebock/ansible-role-bootstrap#26]
**Is your feature request related to a problem? Please describe.**
- EOL of python 2.7 
- support for python 3 being stable since ansible 2.5
- ansible firewalld module does not work with Ubuntu 18.04 LTS

**Describe the solution you'd like**
Install python 3 packages instead of python 2 for Ubuntu hosts.

**Describe alternatives you've considered**
Overwrite `bootstrap_apt_packages`, `_bootstrap_packages` and `_bootstrap_stable_packages`.

I can prepare a pull request.

**Comment by robertdebock** [comment]
Good idea. I'm going to guess more distributions are going to use python3.

Thanks for the help @acrom18.

**Comment by jkirk** [comment]
Yes, we just tried python3 with Debian/stretch and it failed. Support for python3 is highly requested. Thx!

**Comment by robertdebock** [comment]
I hope I can fix this in the role, but it's quite a mess.

Ansible 2.8 supports [Python version discovery](https://docs.ansible.com/ansible/devel/porting_guides/porting_guide_2.8.html#python-interpreter-discovery) using a [distribution map](https://github.com/ansible/ansible/blob/183ba93ba39f8590af8e36144c3174920acbe321/lib/ansible/config/base.yml#L1375) followed by a [fallback list](https://github.com/ansible/ansible/blob/183ba93ba39f8590af8e36144c3174920acbe321/lib/ansible/config/base.yml#L1391).

This is an [annoyance](https://travis-ci.org/robertdebock/ansible-role-bootstrap/jobs/535435209) to me too so if I find a solution; it'd make me very happy.

Thanks for expressing your urgency by the way.

**Comment by eby** [comment]
Another option for Ubuntu is to check if the `/usr/bin/python` exists and if not create a symlink to python3. 

I used to do this for the Ubuntu hosts as a bootstrap but since I deal only with Ubuntu these days have been doing `ansible_python_interpreter` in vars. However, the symlink should make ansible back to 2.5 work ok. Not sure if this is a good solution or not though I see your meta has 2.6 as a minimum.

**Comment by tlc** [comment]
I did a little ubuntu-only bootstrap using `ansible_python_interpreter` as well,

    bootstrap_raw_packages: "{{ ansible_python_interpreter | basename }}-minimal"

which I was setting explicitly in the playbook.  I didn't try the discovery values.

You have to be careful in subsequent roles -- anything that installs pip can install the wrong one and drag in python2.

**Comment by robertdebock** [comment]
I think I have a fix now. I'll push some code and let CI test it.

**Comment by robertdebock** [comment]
Hm, it's still not easy; either:
- Use python3 and Ansible 2.8 or later. (or)
- Use python3 and Ansible 2.7 or earlier and set `ansible_python_interpreter`. (or)
- Use python2 until [Ansible 2.9 is out](https://docs.ansible.com/ansible/latest/roadmap/ROADMAP_2_9.html).

The [mapping of distributions and python version](https://github.com/ansible/ansible/blob/faaa669764faba8f2a1b4292afc3bc494e4a1932/lib/ansible/config/base.yml#L1435) has a limited amount of distributions.

**Comment by robertdebock** [comment]
FYI, I'm preparing a large refactor for this role. Currently the list of installed packages is based on just the package manager.
The rewrite of this role intends to gather 2 "facts" (can't really gather facts without python installed):
- bootstrap_distribution
- bootstrap_disitrbution_major_version

With those two variables, it's easier to determine what needs to be installed.

Give me a few more days or [until Ansible 2.9 is released](https://docs.ansible.com/ansible/latest/roadmap/ROADMAP_2_9.html). Currently the 16th of October 2019.

**Comment by robertdebock** [comment]
The large refactor [seems to work](https://travis-ci.org/robertdebock/ansible-role-bootstrap/builds/583691419)

I'm trying to find a good date to pull this branch into master and release with a new version.

**Comment by robertdebock** [comment]
Seems to be okay now, thanks for your input!
