### ISSUE TITLE
Using this role in check_mode causes error

### ISSUE THREAD

**Issue by TheRealJohnDavies** [robertdebock/ansible-role-bootstrap#3]
When running a play with this role, adding the --check flag causes an error and the play fails.  I believe this is because release.stdout is undefined.  In order to fix, add "check_mode: no" to the "register release" task.  This will make the task run even in check mode.

**Comment by robertdebock** [comment]
Thanks, will implement in a moment.

**Comment by robertdebock** [comment]
Turns out it's rather easy to test. Just one remark, if you run this role in check mode agains a box that misses python, it will still show errors. The purpose of this role is to install all required software, so check mode on an un-bootstrapped system will be a challenge.

**Comment by TheRealJohnDavies** [comment]
Hahaha. I guess you're right. Although I include this as part of my "common
role" so when I run my site.yml or any playbook that includes my common
role it won't error out on the first step anymore.  Thanks for the fix!

-- 
John Davies
