### ISSUE TITLE
Add possibility to update package manager caches

### ISSUE THREAD

**Issue by it-praktyk** [robertdebock/ansible-role-bootstrap#30]
I tried to use the [ansible-role-java](https://github.com/robertdebock/ansible-role-java) in conjunction with the ansible-role-bootstrap on containers for those the package cache [was removed](https://github.com/geerlingguy/docker-ubuntu1804-ansible/blob/master/Dockerfile#L14) and observed that installing of packages fail due to lack of data about available packages.

Because of dependent roles use the [`package` Ansible module](https://docs.ansible.com/ansible/latest/modules/package_module.html#package-module) it's not possible to use options `update_cache` available in some modules (e.g. [`yum`](https://docs.ansible.com/ansible/latest/modules/yum_module.html#yum-module)).

I would like to propose to add an additional switch/feature like `update_packages_cache` to the role `ansible-role-bootstrap`.

I can do some work to implement that feature by myself.

What to do you think about that proposal?

**Comment by robertdebock** [comment]
Thanks again for helping.

I would like to keep the bootstrap role as limited as possible, barely enough to _bootstrap_.

Would it be an idea to make a role `ansible-role-update_package_cache` that can be included to people wanting to clear the cache?

I see both [`apt`](https://docs.ansible.com/ansible/latest/modules/apt_module.html) and [`yum`](https://docs.ansible.com/ansible/latest/modules/yum_module.html) have this option.

**Comment by robertdebock** [comment]
I've added that function to [another role](https://galaxy.ansible.com/robertdebock/update_package_cache)

So in your case, you could sequentially run:

```yaml
- name: do-it-all
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - robertdebock.bootstrap
    - robertdebock.update_package_cache
    - robertdebock.java
```

Hope that helps you!

**Comment by it-praktyk** [comment]
Thank you.
