### ISSUE TITLE
Role need Ansible version >=2.8

### ISSUE THREAD

**Issue by rembik** [robertdebock/ansible-role-bootstrap#37]
**Describe the bug**
Because of python3 usage without static declaration of ansible_python_interpreter this role only works for newer linux distributions under use of Ansible 2.8 or higher. 

**To Reproduce**
Run this role with ansible 2.7

**Expected behavior**

**Error**

**Environment**
- Control node OS: [e.g. Debian 9]
- Control node Ansible version: [e.g. 2.7.X]
- Managed node OS: [e.g. CentOS 7]

**Additional context**
Change minimal required ansible version in meta data.

**Comment by robertdebock** [comment]
Still has to be released to Galaxy. I'll close when done.

**Comment by robertdebock** [comment]
Galaxy now show 2.8 as required. Thanks!
