### ISSUE TITLE
minimal centos doesn't have a package python

### ISSUE THREAD

**Issue by fireba11** [robertdebock/ansible-role-bootstrap#40]
in a minimal centos installation the repositories don't have a package python (bad idea if you ask me ...)
you'll need one of those python2 python36 python38 ;-)

**Comment by robertdebock** [comment]
Okay, thanks for the issue. Can you tell me what Docker image or Vagrant image you are using?

**Comment by fireba11** [comment]
It was in my local centOS 8 VM that I use to test my ansible things.
Installed with CentOS-8.1.1911-x86_64-boot.iso with no additional packages.
Afaik that's the smallest installation version available.

**Comment by robertdebock** [comment]
The best I can do it to reproduce with [generic/centos8](https://github.com/lavabit/robox/blob/master/http/generic.centos8.vagrant.ks) which installs `@core`.

That still works well.

Can you show me the repositories you have:

```
dnf repolist
dnf repolist enabled
```

Thanks for you patience!

**Comment by fireba11** [comment]
only got 3 repositories, all are enabled:

CentOS-8 - AppStream
CentOS-8 - Base
CentOS-8 - Extras

**Comment by robertdebock** [comment]
Sorry, I can't reproduce this issue. Feel free to open it when there is a way to test/reproduce this.
