### ISSUE TITLE
Can the bootstrap_user log in without being root?

### ISSUE THREAD

**Issue by bbaassssiiee** [robertdebock/ansible-role-bootstrap#51]
https://github.com/robertdebock/ansible-role-bootstrap/blob/c48df547090c78ac3174d293edd2866a868e292a/tasks/main.yml#L66

**Comment by bbaassssiiee** [comment]
bootstrap_ansible_user is undocumented

**Comment by robertdebock** [comment]
Version 6.0.0 removed a custom user.
