### ISSUE TITLE
Impossible to install any package excepting when I am root user.

### ISSUE THREAD

**Issue by Pandemonium1986** [robertdebock/ansible-role-bootstrap#53]
## Describe the bug

According to the business logic the user who installs a package is the user retrieved in `bootstrap_ansible_user`.
This one is `bootstrap_user` if and only if we could not connect with the `remote_user`.

In the case of using a privileged user (in my case `vagrant` which is a user sudoers without a password). The `install bootstrap packages (package)` task can never finish properly because only root can install a package. This is impossible to be "root" due to the become_user key on this task.

## Playbook
Use the example playbook on the README.md file

```yaml
---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
```
Be sure to have a privileged user on managed node or try to do it with vagrant :

## Output
```
TASK [robertdebock.bootstrap : install bootstrap packages name={{ item }}, state=present] ****************************************************************************************************************************************************
Monday 25 October 2021  23:33:38 +0200 (0:00:00.694)       0:00:01.286 ******** 
failed: [127.0.0.1] (item=python3) => changed=false 
  ansible_loop_var: item
  item: python3
  msg: This command has to be run under the root user.
  results: []
failed: [127.0.0.1] (item=sudo) => changed=false 
  ansible_loop_var: item
  item: sudo
  msg: This command has to be run under the root user.
  results: []
```

## Environment

Only test with Centos-8
Step by Step to reproduce :

```sh
ansible-galaxy install robertdebock.bootstrap
mkdir /tmp/vagrant
vagrant init generic/centos8 --box-version 3.4.2 
vgt up
vim play.yml 
---
- name: Converge
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
  
ansible-playbook -i '127.0.0.1:2200,' --private-key ./.vagrant/machines/default/virtualbox/private_key -b -u vagrant play.yml
```

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
You are correct; this is a bit of an issue with this logic; the role assumes that a machine does not have `sudo` or `python` (`python3`, `python-3`, or something related) installed.
So; the role needs to run as root initially to install these packages. Specifically `sudo` must be installed using the `root` account.

One thing that caught my attention: `become: yes` (from `README.md`). Becoming is only available after `sudo` is installed. [Trying](https://github.com/robertdebock/ansible-role-bootstrap/actions/runs/1384496712) that [now](https://github.com/robertdebock/ansible-role-bootstrap/commit/ec59eb31bc5c565e72623c4af915f53edb7e3c5d).

**Comment by Pandemonium1986** [comment]
Interesting they all suffer from the same problem. Due to the `become: no` the task try to become smthg with  `sudo` wich is the default behaviour of `become_method`. I suppose it work on the other os like debian because `sudo` is available on the docker image (natively). Anyway don't spend time for this. I understand that the role assume than python3 and sudo should not available on the managed node and the only way to manage that is ... to be root and only root :-)
