### ISSUE TITLE
README Galaxy role downloads badge fix

### ISSUE THREAD

**Issue by buluma** [robertdebock/ansible-role-bootstrap#71]
# Proposed feature

Got a fix for the download badge.

`|GitHub|GitLab|Downloads|Version|
|------|------|---------|-------|
|[![github](https://github.com/robertdebock/ansible-role-bootstrap/workflows/Ansible%20Molecule/badge.svg)](https://github.com/robertdebock/ansible-role-bootstrap/actions)|[![gitlab](https://gitlab.com/robertdebock-iac/ansible-role-bootstrap/badges/master/pipeline.svg)](https://gitlab.com/robertdebock-iac/ansible-role-bootstrap)|[![downloads](https://img.shields.io/ansible/role/d/24451)](https://galaxy.ansible.com/robertdebock/bootstrap)|[![Version](https://img.shields.io/github/release/robertdebock/ansible-role-bootstrap.svg)](https://github.com/robertdebock/ansible-role-bootstrap/releases/)|`

'https://img.shields.io/ansible/role/d/24451' moved [here:: badges/ansible-role](https://shields.io/badges/ansible-role)

gives you

![Ansible Role](https://img.shields.io/ansible/role/d/robertdebock/bootstrap)

## Rationale

Track your downloads as usual before everything went bananas.

## Additional context

Happy holidays mate.

Please consider [sponsoring me](https://github.com/sponsors/robertdebock).

**Comment by robertdebock** [comment]
Thanks man! Adjusting my roles now.
